using RD2LPowerRankings.Services.DotaRanking.Enums;

namespace RD2LPowerRankings.Modules.Dota;

public class PlayerWordWeights
{
    public static readonly List<KeyValuePair<string, DotaEnums.WordToxicity>> WordWeights = new()
    {
        new KeyValuePair<string, DotaEnums.WordToxicity>("xd", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("fuck", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("idiot", DotaEnums.WordToxicity.Toxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("report", DotaEnums.WordToxicity.Toxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("ez", DotaEnums.WordToxicity.NotNiceAtAll),
        new KeyValuePair<string, DotaEnums.WordToxicity>("retard", DotaEnums.WordToxicity.PoliticallyIncorrect),
        new KeyValuePair<string, DotaEnums.WordToxicity>("garbage", DotaEnums.WordToxicity.Toxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("clueless", DotaEnums.WordToxicity.Toxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("this", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("ty", DotaEnums.WordToxicity.Wholesome),
        new KeyValuePair<string, DotaEnums.WordToxicity>("gg", DotaEnums.WordToxicity.Wholesome),
        new KeyValuePair<string, DotaEnums.WordToxicity>("lol", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("glhf", DotaEnums.WordToxicity.Wholesome),
        new KeyValuePair<string, DotaEnums.WordToxicity>("please", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("lmao", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("cant", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("when", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("god", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("lmfao", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("gay", DotaEnums.WordToxicity.Homophobic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("trash", DotaEnums.WordToxicity.NotNiceAtAll),
        new KeyValuePair<string, DotaEnums.WordToxicity>("noob", DotaEnums.WordToxicity.NotNiceAtAll),
        new KeyValuePair<string, DotaEnums.WordToxicity>("dick", DotaEnums.WordToxicity.Sexist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("bitch", DotaEnums.WordToxicity.Sexist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("literally", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("support", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("wards", DotaEnums.WordToxicity.NotNiceAtAll),
        new KeyValuePair<string, DotaEnums.WordToxicity>("understand", DotaEnums.WordToxicity.NotNiceAtAll),
        new KeyValuePair<string, DotaEnums.WordToxicity>("pussy", DotaEnums.WordToxicity.Sexist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("peru", DotaEnums.WordToxicity.ModeratelyRacist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("stfu", DotaEnums.WordToxicity.VeryToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("brain", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("mute", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("feed", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("english", DotaEnums.WordToxicity.SlightlyRacist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("women", DotaEnums.WordToxicity.Sexist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("congrats", DotaEnums.WordToxicity.Wholesome),
        new KeyValuePair<string, DotaEnums.WordToxicity>("stupid", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("jesus", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("legend", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("ancient", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("monkey", DotaEnums.WordToxicity.NotNiceAtAll),
        new KeyValuePair<string, DotaEnums.WordToxicity>("honest", DotaEnums.WordToxicity.Toxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("ape", DotaEnums.WordToxicity.Toxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("ping", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("girl", DotaEnums.WordToxicity.Sexist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("idc", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("rekt", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("penis", DotaEnums.WordToxicity.Sexist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("cry", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("grats", DotaEnums.WordToxicity.VeryWholesome),
        new KeyValuePair<string, DotaEnums.WordToxicity>("wp", DotaEnums.WordToxicity.Wholesome),
        new KeyValuePair<string, DotaEnums.WordToxicity>("crusader", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("virgin", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("taco", DotaEnums.WordToxicity.ModeratelyRacist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("fag", DotaEnums.WordToxicity.VeryHomophobic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("slut", DotaEnums.WordToxicity.Sexist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("cunt", DotaEnums.WordToxicity.Sexist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("chin", DotaEnums.WordToxicity.Racist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("chong", DotaEnums.WordToxicity.Racist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("jaja", DotaEnums.WordToxicity.Toxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("bean", DotaEnums.WordToxicity.Racist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("spic", DotaEnums.WordToxicity.Racist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("nigg", DotaEnums.WordToxicity.Racist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("spicy", DotaEnums.WordToxicity.RacistFalsePositive),
        new KeyValuePair<string, DotaEnums.WordToxicity>("spice", DotaEnums.WordToxicity.RacistFalsePositive),
        new KeyValuePair<string, DotaEnums.WordToxicity>("yourself", DotaEnums.WordToxicity.NotNiceAtAll),
        new KeyValuePair<string, DotaEnums.WordToxicity>("deserve", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("easiest", DotaEnums.WordToxicity.NotNice),
        new KeyValuePair<string, DotaEnums.WordToxicity>("useless", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("boosted", DotaEnums.WordToxicity.Toxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("end", DotaEnums.WordToxicity.Toxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("moms", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("mother", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("dumbass", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("cock", DotaEnums.WordToxicity.Sexist),
        new KeyValuePair<string, DotaEnums.WordToxicity>("smurf", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("wreck", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("jungl", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("zero", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("these", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("expect", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("jbay", DotaEnums.WordToxicity.SlightlyToxic),
        new KeyValuePair<string, DotaEnums.WordToxicity>("vvodle", DotaEnums.WordToxicity.VeryWholesome),
        new KeyValuePair<string, DotaEnums.WordToxicity>("disrespect", DotaEnums.WordToxicity.NotNiceAtAll),
        new KeyValuePair<string, DotaEnums.WordToxicity>("think", DotaEnums.WordToxicity.NotNiceAtAll),
        new KeyValuePair<string, DotaEnums.WordToxicity>("typical", DotaEnums.WordToxicity.NotNiceAtAll)
    };
}